### ISSUE TITLE
images on watchy v2 not showing

### ISSUE THREAD

**Issue by stweise** [Michal-Szczepaniak/TinyWatchy#2]
Tried to make the default face work and stumbled into a few issues.

I tried to better document how to get started and hope it helps get more people going more easily. see #1 

However, the images are not showing properly with a watchy v2 (china copy). That may be due to something I did with xxd.

Can you help me figure this out?
![IMG_5635](https://github.com/user-attachments/assets/d56e89e7-2f68-4665-b616-56e29286a088)

**Comment by Michal-Szczepaniak** [comment]
That was easy fix :D Please write how you fixed it for future internet people

On Sunday, 29 September 2024, Steffen Weise wrote:
> Closed #2 as completed.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/Michal-Szczepaniak/TinyWatchy/issues/2#event-14445964519
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***

-- 
Sent from my Sailfish device
